ci:
  autofix: true
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
        exclude: \.clang-format$
      - id: check-json
      - id: check-xml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-merge-conflict
  ######################################################################
  # Python Formatting
  ######################################################################
  # For Python import sorting
  - repo: https://github.com/pycqa/isort
    rev: "5.12.0"
    hooks:
      - id: isort
  # Yet Another Python Formatter
  - repo: https://github.com/pre-commit/mirrors-yapf
    rev: v0.32.0
    hooks:
      - id: yapf
        additional_dependencies: [toml]
  - repo: https://github.com/PyCQA/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        args:
          - --max-line-length=120
          - --ignore=E203,E501,W503,W504,F541
  ######################################################################
  # Yaml Formatting
  ######################################################################
  - repo: https://github.com/google/yamlfmt
    rev: v0.14.0
    hooks:
      - id: yamlfmt
        files: \.(yaml|yml)$
  ######################################################################
  # Markdown Formatting
  ######################################################################
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.9
    hooks:
      - id: mdformat
        exclude: 'github/'
  ######################################################################
  # C++ Formatting
  ######################################################################
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v16.0.6 # Version of clang-format
    hooks:
      - id: clang-format
        files: \.(cpp|h|hpp)$ # Only check C++ and header files
        exclude: cpp/trg_planner/core/trg_planner/include/kdtree|cpp/trg_planner/core/trg_planner/src/kdtree # Exclude kdtree files
  - repo: https://github.com/cpplint/cpplint
    rev: "1.6.1"
    hooks:
      - id: cpplint
        args: ["--filter=-whitespace/line_length,-legal/copyright,-build/include_order,-runtime/references,-build/c++11,-build/namespaces,-build/include_what_you_use,-build/include_subdir"]
        exclude: cpp/trg_planner/core/trg_planner/include/kdtree|cpp/trg_planner/core/trg_planner/src/kdtree # Exclude kdtree files
